FROM postgres:13

ENV POSTGRES_DB=db

# Passwords stored under .env
COPY .env /app/.env

COPY init.sql /docker-entrypoint-initdb.d/

#Seed a few artworks in for testing.
COPY seed/seed.sql /docker-entrypoint-initdb.d/
COPY seed/mona-lisa.jpg /docker-entrypoint-initdb.d/seed-data/
COPY seed/the-last-supper.jpg /docker-entrypoint-initdb.d/seed-data/
COPY seed/vitruvian-man.jpg /docker-entrypoint-initdb.d/seed-data/
COPY seed/creation-of-adam.jpg /docker-entrypoint-initdb.d/seed-data/

EXPOSE 5432
